/* Generated By:JJTree: Do not edit this line. ASTQuantifiedSymbolsDefs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package b.parser;

public
class ASTQuantifiedSymbolsDefs extends SimpleNode {
    public ASTQuantifiedSymbolsDefs(int id) {
        super(id);
    }

    public ASTQuantifiedSymbolsDefs(BParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(BParserVisitor visitor, java.util.Map<Object, Object> data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=db90d9cca59ee6a1b80822a42c3ef0f9 (do not edit this line) */
