/* Generated By:JJTree: Do not edit this line. ASTQuantifiedFunDef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package b.parser;

public
class ASTQuantifiedFunDef extends SimpleNode {
    public ASTQuantifiedFunDef(int id) {
        super(id);
    }

    public ASTQuantifiedFunDef(BParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(BParserVisitor visitor, java.util.Map<Object, Object> data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=29b23f6448cb9743fae36b9b230ca9a8 (do not edit this line) */
