/* Generated By:JavaCC: Do not edit this line. BParserVisitor.java Version 5.0 */
package b.parser;

public interface BParserVisitor {
    Object visit(SimpleNode node, java.util.Map<Object, Object> data);

    Object visit(ASTMachine node, java.util.Map<Object, Object> data);

    Object visit(ASTExpr node, java.util.Map<Object, Object> data);

    Object visit(ASTPlus node, java.util.Map<Object, Object> data);

    Object visit(ASTMinus node, java.util.Map<Object, Object> data);

    Object visit(ASTTimes node, java.util.Map<Object, Object> data);

    Object visit(ASTDiv node, java.util.Map<Object, Object> data);

    Object visit(ASTMod node, java.util.Map<Object, Object> data);

    Object visit(ASTIdentifier node, java.util.Map<Object, Object> data);

    Object visit(ASTNumber node, java.util.Map<Object, Object> data);
}
/* JavaCC - OriginalChecksum=8393bed953de51009b2c6604a1ca9d9b (do not edit this line) */
