/* Generated By:JavaCC: Do not edit this line. BParserTreeConstants.java Version 5.0 */
package b.parser;

public interface BParserTreeConstants {
    int JJTMACHINE = 0;
    int JJTEXPR = 1;
    int JJTPLUS = 2;
    int JJTMINUS = 3;
    int JJTVOID = 4;
    int JJTTIMES = 5;
    int JJTDIV = 6;
    int JJTMOD = 7;
    int JJTIDENTIFIER = 8;
    int JJTNUMBER = 9;


    String[] jjtNodeName = {
            "Machine",
            "Expr",
            "Plus",
            "Minus",
            "void",
            "Times",
            "Div",
            "Mod",
            "Identifier",
            "Number",
    };
}
/* JavaCC - OriginalChecksum=d915b386e4034771f0dd657bde26ef53 (do not edit this line) */
