/* Generated By:JJTree&JavaCC: Do not edit this line. BParserConstants.java */
package b.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BParserConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int MACHINE = 5;
    /**
     * RegularExpression Id.
     */
    int CONST_DEFS = 6;
    /**
     * RegularExpression Id.
     */
    int SET_DEFS = 7;
    /**
     * RegularExpression Id.
     */
    int VAR_DEFS = 8;
    /**
     * RegularExpression Id.
     */
    int FUN_DEFS = 9;
    /**
     * RegularExpression Id.
     */
    int INVARIANT = 10;
    /**
     * RegularExpression Id.
     */
    int INITIALISATION = 11;
    /**
     * RegularExpression Id.
     */
    int SUB_SKIP = 12;
    /**
     * RegularExpression Id.
     */
    int ASSIGN = 13;
    /**
     * RegularExpression Id.
     */
    int TO = 14;
    /**
     * RegularExpression Id.
     */
    int EQUIV = 15;
    /**
     * RegularExpression Id.
     */
    int IMPLIES = 16;
    /**
     * RegularExpression Id.
     */
    int OR = 17;
    /**
     * RegularExpression Id.
     */
    int AND = 18;
    /**
     * RegularExpression Id.
     */
    int EQ = 19;
    /**
     * RegularExpression Id.
     */
    int NOT = 20;
    /**
     * RegularExpression Id.
     */
    int NEQ = 21;
    /**
     * RegularExpression Id.
     */
    int LT = 22;
    /**
     * RegularExpression Id.
     */
    int LE = 23;
    /**
     * RegularExpression Id.
     */
    int GT = 24;
    /**
     * RegularExpression Id.
     */
    int GE = 25;
    /**
     * RegularExpression Id.
     */
    int IN = 26;
    /**
     * RegularExpression Id.
     */
    int FALSE = 27;
    /**
     * RegularExpression Id.
     */
    int TRUE = 28;
    /**
     * RegularExpression Id.
     */
    int MINUS = 29;
    /**
     * RegularExpression Id.
     */
    int PLUS = 30;
    /**
     * RegularExpression Id.
     */
    int TIMES = 31;
    /**
     * RegularExpression Id.
     */
    int DIV = 32;
    /**
     * RegularExpression Id.
     */
    int MOD = 33;
    /**
     * RegularExpression Id.
     */
    int DOUBLE = 34;
    /**
     * RegularExpression Id.
     */
    int INT = 35;
    /**
     * RegularExpression Id.
     */
    int DIGIT = 36;
    /**
     * RegularExpression Id.
     */
    int ENUMVALUE = 37;
    /**
     * RegularExpression Id.
     */
    int IDENTIFIER = 38;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"\\r\"",
            "\"\\t\"",
            "\"\\n\"",
            "\"MACHINE\"",
            "<CONST_DEFS>",
            "<SET_DEFS>",
            "<VAR_DEFS>",
            "<FUN_DEFS>",
            "<INVARIANT>",
            "<INITIALISATION>",
            "\"SKIP\"",
            "\":=\"",
            "\"->\"",
            "<EQUIV>",
            "<IMPLIES>",
            "\"||\"",
            "\"&&\"",
            "\"=\"",
            "\"!\"",
            "<NEQ>",
            "\"<\"",
            "\"<=\"",
            "\">\"",
            "\">=\"",
            "\":\"",
            "\"false\"",
            "\"true\"",
            "\"-\"",
            "\"+\"",
            "\"*\"",
            "\"/\"",
            "\"%\"",
            "<DOUBLE>",
            "<INT>",
            "<DIGIT>",
            "<ENUMVALUE>",
            "<IDENTIFIER>",
            "\"(\"",
            "\")\"",
            "\"{\"",
            "\",\"",
            "\"}\"",
    };

}
