/* Generated By:JavaCC: Do not edit this line. BParserTreeConstants.java Version 5.0 */
package b.parser;

public interface BParserTreeConstants {
    int JJTMACHINE = 0;
    int JJTEXPR = 1;
    int JJTEQUIV = 2;
    int JJTVOID = 3;
    int JJTIMPLIES = 4;
    int JJTOR = 5;
    int JJTAND = 6;
    int JJTEQ = 7;
    int JJTIN = 8;
    int JJTLT = 9;
    int JJTLE = 10;
    int JJTGT = 11;
    int JJTGE = 12;
    int JJTPLUS = 13;
    int JJTMINUS = 14;
    int JJTTIMES = 15;
    int JJTDIV = 16;
    int JJTMOD = 17;
    int JJTNOT = 18;
    int JJTUMINUS = 19;
    int JJTIDENTIFIER = 20;
    int JJTFALSE = 21;
    int JJTTRUE = 22;
    int JJTDOUBLE = 23;
    int JJTINT = 24;
    int JJTEMPTYSET = 25;
    int JJTSEQ = 26;
    int JJTSET = 27;


    String[] jjtNodeName = {
            "Machine",
            "Expr",
            "Equiv",
            "void",
            "Implies",
            "Or",
            "And",
            "Eq",
            "In",
            "LT",
            "LE",
            "GT",
            "GE",
            "Plus",
            "Minus",
            "Times",
            "Div",
            "Mod",
            "Not",
            "UMinus",
            "Identifier",
            "False",
            "True",
            "Double",
            "Int",
            "EmptySet",
            "Seq",
            "Set",
    };
}
/* JavaCC - OriginalChecksum=0daad7d29d03eb9f9be79ab2f3e2c4aa (do not edit this line) */
