/* Generated By:JavaCC: Do not edit this line. BParserVisitor.java Version 5.0 */
package b.parser;

public interface BParserVisitor {
    Object visit(SimpleNode node, Object data);

    Object visit(ASTMachine node, Object data);

    Object visit(ASTExpr node, Object data);

    Object visit(ASTPlus node, Object data);

    Object visit(ASTMinus node, Object data);

    Object visit(ASTTimes node, Object data);

    Object visit(ASTDiv node, Object data);

    Object visit(ASTMod node, Object data);

    Object visit(ASTIdentifier node, Object data);

    Object visit(ASTNumber node, Object data);
}
/* JavaCC - OriginalChecksum=b0cc0ff82bd6e32f07cb2dc5406144ac (do not edit this line) */
