/* Generated By:JJTree: Do not edit this line. ASTConstDefs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package b.parser;

public
class ASTConstDefs extends SimpleNode {
    public ASTConstDefs(int id) {
        super(id);
    }

    public ASTConstDefs(BParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(BParserVisitor visitor, java.util.Map<Object, Object> data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=ae942f1f70f24d5c07cbb8a0562cbb1f (do not edit this line) */
